# Filename of the project's main sketch
sketch: EspTest.ino
# Sketch version (optional; appended to filename of compiled binary file)
version: 1.0.0

# Compilation target
target:
  
  # Arduino core name
  core: esp32:esp32      # Installs the latest version; or
  # Arduino board FQBN string (obtained from `arduino-cli board list`)
  board: esp32:esp32:esp32
  # Additional board manager URL for core installation (optional)
  url: https://dl.espressif.com/dl/package_esp32_index.json

# Libraries to be included for compilation
libraries:
  - ArduinoJson
  - EspMQTTClient
  - Adafruit MPU6050
  - Adafruit SSD1306
  - MPU6050_tockn
  - PubSubClient
  - WiFi
  
  # - Arduino Low Power==1.2.1  # Installs v1.2.1
